export const Constants = {
    EMPTY_STRING: '',

    FIRST_PAGE_INDEX: 0,
    MAX_TASKS_PER_PAGE: 5,
    MAX_PAGINATION_PAGES: 5,

    FILTER_ALL: 'FILTER_ALL',
    FILTER_UNDONE: 'FILTER_UNDONE',
    FILTER_DONE: 'FILTER_DONE',

    DATE_FILTER_DIRECTION_UP: 'DATE_FILTER_DIRECTION_UP',
    DATE_FILTER_DIRECTION_DOWN: 'DATE_FILTER_DIRECTION_DOWN'
};